openapi: 3.0.3
info:
  title: Theater Management API
  description: API for managing theaters, including CRUD operations.
  version: 1.0.0
servers:
  - url: /api/theatres
    description: Base URL for the Theater Management API
paths:
  /{theatreId}:
    get:
      summary: Get a theater by ID
      description: Retrieve details of a theater by its unique ID.
      parameters:
        - name: theatreId
          in: path
          required: true
          description: The ID of the theater to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: Theater retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theatre'
        '404':
          description: Theater not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a theater
      description: Update the details of an existing theater.
      parameters:
        - name: theatreId
          in: path
          required: true
          description: The ID of the theater to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Theatre'
      responses:
        '200':
          description: Theater updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theatre'
        '404':
          description: Theater not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a theater
      description: Delete an existing theater by its ID.
      parameters:
        - name: theatreId
          in: path
          required: true
          description: The ID of the theater to delete.
          schema:
            type: integer
      responses:
        '204':
          description: Theater deleted successfully.
        '404':
          description: Theater not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /:
    post:
      summary: Add a new theater
      description: Add a new theater to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Theatre'
      responses:
        '201':
          description: Theater added successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theatre'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /list:
    post:
      summary: Get theaters by IDs
      description: Retrieve a list of theaters by their IDs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
      responses:
        '200':
          description: List of theaters retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Theatre'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Theatre:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the theater.
        name:
          type: string
          description: Name of the theater.
        city:
          type: string
          description: City where the theater is located.
        address:
          type: string
          description: Address of the theater.
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the theater was created.
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the theater was last updated.
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP status code.
        message:
          type: string
          description: Error message.